cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.cart_summary, name='cart_summery'),
    path('add/', views.cart_add, name='cart_add'),
    path('remove/<int:cart_item_id>/', views.remove_from_cart, name='delete_from_cart'),

]

digikala/urls.py
from django.contrib import admin
from django.urls import path,include
from shop.views import home_page
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path("", home_page,name="home"),
    path("shop/", include('shop.urls')),
    path("cart/", include('cart.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from shop.views import home_page, about, login_user, logout_user, register_user, category, product,search


urlpatterns = [
    path('', home_page, name='home'),
    path('about/', about, name='about'),
    path('login/', login_user, name='login_user'),
    path('register/', register_user, name='register_user'),
    path('product/<int:pk>/', product, name='product'),
    path('logout/', logout_user, name='logout_user'),
    path('search/', search, name='search'),
    path('category/<str:cat>/',category, name='Category')
]

shop/models.py
from django.db import models
import datetime


class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class Customer(models.Model):
        firs_name = models.CharField(max_length=20)
        last_name = models.CharField(max_length=20)
        email = models.EmailField()
        phone = models.CharField(max_length=20)
        password = models.CharField(max_length=20)

        def __str__(self):
            return self.name

class Products(models.Model):
            name = models.CharField(max_length=20)
            description = models.TextField(blank=True)
            category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)
            price = models.DecimalField(max_digits=20, decimal_places=2)
            picture = models.ImageField(upload_to='upload/Product/')

            is_sale = models.BooleanField(default=False)
            sale_price = models.DecimalField( default= 0 ,max_digits=20,decimal_places=2)

            def __str__(self):
                return self.name

class Order(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    address = models.CharField(max_length=30)
    phone_number = models.CharField(max_length=20)
    quantity = models.IntegerField(default=1)
    date = models.DateTimeField(datetime.datetime.today())
    status = models.BooleanField(default=False)

    def __str__(self):
     return self.product

shop/forms.py
# from django import forms
# from django.contrib.auth.forms import UserCreationForm
# from django.core import validators
# from django.contrib.auth.models import User
#
# class register_form(UserCreationForm):
#     first_name = forms.CharField(
#         widget=forms.TextInput(attrs={'placeholder': "لطفا نام کاربری را وارد کنید  "}),
#         label="Username",
#         validators=[
#             validators.MaxLengthValidator(limit_value=20, message="Username must be at most 20 characters."),
#             validators.MinLengthValidator(8, message="Username must be at least 8 characters.")
#         ]
#     )
#
#     email = forms.EmailField(
#         widget=forms.EmailInput(attrs={'placeholder': "ایمیل را وارد کنید "}),
#         label="Email",
#         validators=[validators.MaxLengthValidator(limit_value=20, message="Invalid email.")]
#     )
#
#     class Meta:
#         model = User
#         fields = ['first_name', 'email', 'password1', 'password2']
#
#     def clean(self):
#         cleaned_data = super().clean()
#         password = cleaned_data.get("password")
#         re_password = cleaned_data.get("re_password")
#
#         if password and re_password and password != re_password:
#             raise forms.ValidationError("Passwords do not match.")
#
#     def save(self):
#         user_name = self.cleaned_data["user_name"]
#         email = self.cleaned_data["email"]
#         password = self.cleaned_data["password"]
#         User.objects.create_user(username=user_name, email=email, password=password)
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core import validators
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': "Enter username"}),
        label="Username",
        validators=[
            validators.MaxLengthValidator(limit_value=20, message="Username must be at most 20 characters."),
            validators.MinLengthValidator(8, message="Username must be at least 8 characters.")
        ]
    )

    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'placeholder': "Enter email"}),
        label="Email",
        validators=[validators.MaxLengthValidator(limit_value=20, message="Invalid email.")]
    )

    class Meta:
        model = User
        fields = ['first_name', 'email', 'password1', 'password2']

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords do not match.")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

shop/views.py
from django.shortcuts import render, redirect

from cart.cart import Cart
from .models import (Products,Category)
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import User
from .forms import RegisterForm
from django.db.models import Q
# home page 
def home_page(request):
    products = Products.objects.all()
    return render(request, "index.html", {'products': products})

# about as page website 
def about(request):
    return render(request, "about.html")

#login user information page
def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'با موافقیت وارد شدید ')
            return redirect('home')
        else:
            messages.error(request, "مجدد وارد شوید ")
            return redirect("login_user")
    else:
        return render(request, "login.html")

#register user informations 
def register_user(request):
    if request.user.is_authenticated:
        return redirect("home")

    register_form = RegisterForm(request.POST or None)
    if request.method == 'POST':
        if register_form.is_valid():
            user_name = register_form.cleaned_data.get('first_name')
            password = register_form.cleaned_data.get('password1')
            email = register_form.cleaned_data.get('email')
            User.objects.create_user(username=user_name, password=password, email=email)
            messages.success(request, 'حساب کاربری شما با موفقیت ساخته شد .')
            return redirect("login_user")
        else:
            context = {'register_form': register_form}
            return render(request, "Register.html", context)

    context = {'register_form': register_form}
    return render(request, "Register.html", context)

#logout page
def logout_user(request):
    logout(request)
    messages.success(request, "خروج شما با موفقیت انجام شد ")
    return render(request, "logout.html")

#product page query set datebass 
def product(request, pk):
    products = Products.objects.get(id=pk)
    return render(request, "product.html", {'products': products})

#category product
def category(request, cat):
    cat = cat.replace("-", " ")
    try:
        category = Category.objects.get(name=cat)
        products = Products.objects.filter(category=category)
        return render(request, "category.html", {'products': products, 'category': category})
    except Category.DoesNotExist:
        return redirect("home")

#search box viwe:
def search(request):
    if request.method == "POST":
        search = request.POST['search']
        if not search:
            messages.error(request, "لطفا اسم محصول را وارد کنید ")
            return render(request, "search.html", {})
        products = Products.objects.filter(Q(name__icontains=search) | Q(description__icontains=search))
        if not products:
            messages.info(request, "محصولی یافت نشد.")
        return render(request, "search.html", {'products': products, 'search': search})
    else:
        return render(request, "search.html", {})

shop/templates/Register.html
{% extends 'base.html' %}
{% block content %}
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">ثبت نام</h1>
                <p class="lead fw-normal text-white-50 mb-0">حساب کاربری جدید</p>
            </div>
        </div>
    </header>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-xl-7">
                <div class="card border-0 shadow-lg my-5">
                    <div class="card-body p-5">
                        <h2>ایجاد حساب کاربری </h2>
                        <form method="post" action="{% url 'register_user' %}">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="id_first_name" class="form-label">Username</label>
                                <input type="text" name="first_name" class="form-control" id="id_first_name" placeholder="لطفا نام کاربری را وارد کنید">
                                {{ register_form.first_name.errors }}
                            </div>
                            <div class="mb-3">
                                <label for="id_email" class="form-label">Email</label>
                                <input type="email" name="email" class="form-control" id="id_email" placeholder="ایمیل را وارد کنید">
                                {{ register_form.email.errors }}
                            </div>
                            <div class="mb-3">
                                <label for="id_password1" class="form-label">Password</label>
                                <input type="password" name="password1" class="form-control" id="id_password1" placeholder="پسورد خود را وارد کنید">
                               {{ register_form.password1.errors }}
                            </div>
                            <div class="mb-3">
                                <label for="id_password2" class="form-label">Re-enter Password</label>
                                <input type="password" name="password2" class="form-control" id="id_password2" placeholder="مجدد پسورد خود را وارد کنید">
                                {{ register_form.password2.errors }}
                            </div>
                            <button type="submit" class="btn btn-primary">Register</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

shop/templates/base.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>فروشگاه الین شاپ  </title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href={% static "assets/favicon.ico" %} />
        <!-- Bootstrap icons-->
        <link href= "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static "css/styles.css" %} rel="stylesheet" />
        <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    </head>
    <body dir="rtl">
    <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">فروشگاه من </h1>
                    <p class="lead fw-normal text-white-50 mb-0">به فروشگاه الین شاپ خوش امدید   </p>
                </div>
            </div>
        </header>

            <!-- Navigation-->
            {% include 'navbar.html' %}
                {% if messages%}
                              {% for messages in messages  %}
                                  <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                        {{ messages }}
                                      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                  </div>
                              {% endfor %}
                {% endif %}
        {% block content %}
        {% endblock %}
    <br>
    <
    <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white"> elleinshop </p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        </body>
        </html>

shop/templates/category.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
    <div class="container">
        <br>
        <br>
        <br>
        <div class="card mb-3" style="max-width: 540px;">
            <div class="row g-0">
                {% for item in products %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <img class="card-img-top" src="{{ item.picture.url }}" alt="..." />
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <h5 class="fw-bolder">{{ item.name }}</h5>
                                    {% if item.is_sale %}
                                        <strike>{{ item.price | intcomma }}</strike>
                                        <br>
                                        {{ item.sale_price | intcomma }}تومان
                                    {% else %}
                                        {{ item.price | intcomma }}تومان
                                    {% endif %}
                                    <p>{{ item.description }}</p>
                                </div>
                            </div>
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'product' item.id %}">برو به صفحه محصول</a></div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

shop/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
<!-- Section-->
        {% block content %}
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                   {% for item in products %}
                       {% if item.is_sale %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">تخفیف ویژه </div>
                            <img class="card-img-top" src="{{ item.picture.url }}" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{item.name}}</h5>
                                    <strike>{{ item.price | intcomma}}</strike>
                                    <br>
                                    {{ item.sale_price | intcomma}}تومان
                                </div>
                            </div>
                            {{ item.description }}
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href={% url 'product' item.id %}>برو به صفحه محصول </a></div>
                            </div>
                        </div>
                    </div>
                           {% else %}
                            <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="{{ item.picture.url }}" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{item.name}}</h5>
                                    {{ item.price | intcomma}}تومان
                                </div>
                            </div>
                            {{ item.description }}
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href={% url 'product' item.id %}>برو به صفحه محصول</a></div>
                            </div>
                        </div>
                    </div>
                       {% endif %}
                    {% endfor %}
                    <div class="col mb-5">

                        </div>
                    </div>
                </div>
            </div>
        </section>
        {% endblock %}
    </body>
</html>

shop/templates/login.html
{% extends 'base.html' %}
{% block content %}
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">ورود</h1>
                    <p class="lead fw-normal text-white-50 mb-0">ورود به حساب کاربری  </p>
                </div>
            </div>
        </header>
    <div class="container>"/>
        <div class="row">
             <center>
                 <br>
                 <br>
                <div class="col-8">
                    <p align="justify">
                        <form method="post"action={% url "login_user" %} >
                    {% csrf_token %}
                              <div class="mb-3">
                                <input type="text" class="form-control" name="username" placeholder="لطفا نام کاربری وارد کنید ">
                              </div>
                              <div class="mb-3">
                                <input type="password" class="form-control" name="password" placeholder="لطفا رمز عیور را وارد کنید ">
                              </div>
                              <button type="submit" class="btn btn-primary">وارد شوید </button>
                            </form>
                    </p>
                </div>
                 <br>
                 <br>
              </center>

        </div>
    </div>

{% endblock %}

shop/templates/logout.html
{% extends 'base.html' %}
{% block content %}
             <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">خروج</h1>
                    <p class="lead fw-normal text-white-50 mb-0">خروج از حساب کاربری   </p>
                </div>
            </div>
        </header>
    <div class="container>"/>
        <div class="row">
             <center>
                 <br>
                 <br>
                <div class="col-8">
                    <p align="justify">
                    </p>
                </div>
                 <br>
                 <br>
              </center>

        </div>
    </div>

{% endblock %}

shop/templates/navbar.html
{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href={% url 'home' %}> فروشگاه الین  </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href={% url "home" %}>خانه</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'search' %}">جستوجو محصولات </a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'about' %}">درباره ما</a></li>
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url "logout_user" %}">خروج</a></li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'login_user' %}">ورود</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'register_user' %}">ثبت نام </a></li>
                {% endif %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="{% url 'home' %}" role="button" data-bs-toggle="dropdown" aria-expanded="false">فروشگاه </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'home' %}">محصولات </a></li>
                        <li><a class="dropdown-item" href="{% url 'Category' 'laptop' %}"> لپتاپ </a></li>
                        <li><a class="dropdown-item" href="{% url 'Category' 'ساعت-هوشمند' %}">ساعت هوشمند </a></li>
                        <li><a class="dropdown-item" href="{% url 'Category' 'mobile' %}">موبایل    </a></li>
                        <li><a class="dropdown-item" href="{% url 'Category' 'دوربین' %}">دوربین    </a></li>
                    </ul>
                </li>
            </ul>

            <form class="d-flex">
                <a href="{% url 'cart_summery' %}" class="btn btn-outline-dark" type="submit">
                    <i class="bi-cart-fill me-1"></i>
                    سبد خرید
                    <span class="badge bg-dark text-white ms-1 rounded-pill" id="cart_quantity">{{ products_count }}</span>
                </a>
            </form>
        </div>
    </div>
</nav>
{% endblock %}

shop/templates/product.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        {% if products %}
            <div class="card mb-3"  style="width: 450px; height: 300px;;">
                <div class="row g-0">
                    <div class="col-md-4">
                        <img src="{{ products.picture.url }}" class="img-fluid rounded-start" alt="...">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">{{ products.name }}</h5>
                            <p class="card-text">{{ products.description }}</p>
                            {% if products.is_sale %}
                                <p class="card-text">{{ products.sale_price }}</p>
                            {% else %}
                                <p class="card-text">{{ products.sale_price }}</p>
                            {% endif %}
                        <p class="card-text">تعداد؛</p>
                        {% for key,value in quantity.item %}
                            {% endfor %}
                        <select class="form-select form-select-sm" id="cart_qty">
                          <option value="1">1</option>
                          <option value="2">2</option>
                          <option value="3">3</option>
                          <option value="3">4</option>
                        </select>
                            <br>
                            <a href="{% url 'home' %}" class="btn btn-secondary" >بازگشت به صفحه خرید </a>
                            <br>
                            <button class="btn btn-secondary" type="button" value='{{ products.id }}' id="add_cart">  افزودن به سبد خرید </button>
                            </a>
                        </div>
                    </div>
                 <script>
                       $(document).on("click", '#add_cart', function (e) {
                           e.preventDefault();
                              var productId = $(this).val();
                                    $.ajax({
                                        url: "{% url 'cart_add' %}",
                                        method: "POST",
                                        data: {
                                            product_id: productId,
                                            product_qty: $ ('#cart_qty option:selected').text(),
                                            csrfmiddlewaretoken: '{{ csrf_token }}',
                                            action: 'post'
                                        },
                                        success: function (response) {
                                            document.getElementById('cart_quantity').textContent = response.qty;
                                        },
                                        error: function (xhr, errmsg, err) {
                                            console.error(xhr.status + ": " + xhr.responseText);
                                        }
                                    });
                                });
                 </script>


                </div>
            </div>
        {% else %}
            <p></p>
        {% endif %}
    </div>
{% endblock %}

shop/templates/search.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <p class="lead fw-normal text-white-50 mb-0">جستجوی محصولات مورد نظر</p>
        </div>
    </div>
</header>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                </div>
                <div class="card-body">
                    <form method="post" action="{% url 'search' %}">
                        {% csrf_token %}
                        <div class="mb-3"></div>
                        <input type="text" class="form-control" placeholder="" name="search">
                        <button type="submit" class="btn btn-secondary">جستجوی محصول</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <br>
    <br>
    <br>
    {% if products %}
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        {% for item in products %}
        <div class="col mb-5">
            <div class="card h-100">
                <img class="card-img-top" src="{{ item.picture.url }}" alt="..." />
                <div class="card-body p-4">
                    <div class="text-center">
                        <h5 class="fw-bolder">{{ item.name }}</h5>
                        {% if item.is_sale %}
                        <strike>{{ item.price | intcomma }}</strike>
                        <br>
                        {{ item.sale_price | intcomma }}تومان
                        {% else %}
                        {{ item.price | intcomma }}تومان
                        {% endif %}
                        <p>{{ item.description }}</p>
                    </div>
                </div>
                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'product' item.id %}">برو به صفحه محصول</a></div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock %}